### ISSUE TITLE
How-to

### ISSUE THREAD

**Issue by maciej-nadobnik** [simoncozens/fonticulus#4]
Hi @simoncozens,

I wanted to try out fonticulus. I installed Rust and fonticulus and tried to run like this in command line:
`fonticulus /path/to/file`
which gives me this error:

> thread 'main' panicked at 'Unknown file type "/Users/nadobnikm/Desktop/New Font.UFO"', /Users/nadobnikm/.cargo/registry/src/github.com-1ecc6299db9ec823/fonticulus-0.1.0/src/main.rs:72:9
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Can you please help me out with what I am doing wrong?

Thanks!

**Comment by simoncozens** [comment]
Hi Maciej! Thanks for trying and it looks like you even got it to compile - well done. Currently fonticulus supports .glyphs and .designspace sources but not single UFOs any more. I’ll add that functionality back again soon.

**Comment by maciej-nadobnik** [comment]
Hi @simoncozens, thank you for answering. I get the same response when running on glyphs 2 and glyphs 3 files:

terminal input:
`fonticulus /Users/nadobnikm/Desktop/New\ Font.glyphs`

terminal output:
> thread 'main' panicked at 'Unknown file type "/Users/nadobnikm/Desktop/New Font.glyphs"', /Users/nadobnikm/.cargo/registry/src/github.com-1ecc6299db9ec823/fonticulus-0.1.0/src/main.rs:72:9
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Could there be something wrong with the way I pass the filename or with the file itself?

**Comment by simoncozens** [comment]
OK, I see what it is. There are a few things going on. You are using the first "prerelease" version, which *does* only support UFO. But it expects the file name to end `.ufo` (lower case)! So you should pass a lowercase extension. (And I should fix that bug.)

To support glyphs and designspace you need to compile the latest git version, but that requires a specific directory layout because development is moving so rapidly:

```
% mkdir build; cd build
% git checkout https://github.com/simoncozens/fonttools-rs
% git checkout https://github.com/simoncozens/babelfont-rs
% git checkout https://github.com/simoncozens/fonticulus
% cd fonticulus
% cargo build
```

**Comment by simoncozens** [comment]
Please note that right now many things (including OpenType layout) don't work yet, so have appropriate expectations!

**Comment by maciej-nadobnik** [comment]
Hi @simoncozens, Thank you for the further instructions. The build command got stuck on the _norad_ dependency, apparently version 0.4 is not available anymore. I got it to build after chaning the dependency to 0.5 in fonticulus and babelfont-rs. To use this latest git version now, do I have to run the ’fonticulus’ command with that dir as my working dir?
I do keep in mind the limited functionality!

**Comment by simoncozens** [comment]
The resulting binary will be fonticulus/target/debug/fonticulus (or replace “debug” with “release” if you did “cargo build --release” - highly recommended). You can then copy that binary wherever you want it.
